# Generated by Django 5.1.5 on 2025-01-29 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_answer_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='auther',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='auther',
            new_name='author',
        ),
    ]
